name: Update Momiage Mono Cask

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-momiage-mono:
    runs-on: macos-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 最新リリース情報を取得
        id: get_release
        run: |
          api_url="https://api.github.com/repos/kb10uy/MomiageMono/releases/latest"
          response=$(curl -sL --retry 3 --retry-delay 5 "$api_url")
          # レスポンスが空の場合は他のアプローチから取得
          if [ -z "$response" ]; then
            echo "Error: Failed to fetch release information from GitHub API, trying wget fallback."
            response=$(wget -qO- "$api_url")
            if [ -z "$response" ]; then
              echo "Error: Failed to fetch release information from wget fallback."
              exit 1
            fi
          fi

          # タグ名（バージョン）をそのまま使用
          tag_name=$(echo "$response" | jq -r .tag_name)
          version=${tag_name#v}

          # アセットURLを取得。ただしバージョン番号にハイフンが含まれているため注意。
          asset_url=$(echo "$response" | jq -r '.assets[] | select(.name | contains("MomiageMono")) | .browser_download_url')

          # 取得できなかった場合のURL生成（fallback）
          if [ -z "$asset_url" ]; then
            echo "API didn't return asset URL. Using fallback URL."
            asset_url="https://github.com/kb10uy/MomiageMono/releases/download/${tag_name}/MomiageMono-${tag_name}.zip"
          fi

          # 出力
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "tag_name=$tag_name" >> $GITHUB_OUTPUT
          echo "asset_url=$asset_url" >> $GITHUB_OUTPUT

      - name: SHA256 を計算
        id: compute_sha
        run: |
          if ! curl -sL --retry 3 --retry-delay 5 "${{ steps.get_release.outputs.asset_url }}" -o MomiageMono.zip; then
            echo "Error: Failed to download MomiageMono.zip from ${{ steps.get_release.outputs.asset_url }}"
            exit 1
          fi

          sha256=$(shasum -a 256 MomiageMono.zip | awk '{print $1}')
          echo "sha256=$sha256" >> $GITHUB_OUTPUT

      - name: Cask ファイルを更新
        run: |
          sed -i '' "s/^  version \".*\"/  version \"${{ steps.get_release.outputs.version }}\"/" Casks/momiage-mono.rb
          sed -i '' "s/^  sha256 \".*\"/  sha256 \"${{ steps.compute_sha.outputs.sha256 }}\"/" Casks/momiage-mono.rb

      - name: 変更があるか確認
        id: check_diff
        run: |
          if git diff --quiet Casks/momiage-mono.rb; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: 変更をコミットしてプッシュ
        if: steps.check_diff.outputs.changed == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Casks/momiage-mono.rb
          git commit -m "Updated momiage-mono.rb to version ${{ steps.get_release.outputs.version }}"
          git pull origin --rebase
          git push --force-with-lease